# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: server-production-a7be.up.railway.app
  publicScheme: https
  publicPort: 443

insightsServer:
  port: 8081
  publicHost: server-production-a7be.up.railway.app
  publicScheme: https
  publicPort: 443

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: server-production-a7be.up.railway.app
  publicPort: 443
  publicScheme: https

# Database configuration
database:
  host: shuttle.proxy.rlwy.net    # just the host, no port
  port: 55424                    # Railway DB port
  user: postgres
  password: "bquExGsFrmAdTyWUXcobjEpxtBIqvfso"
  name: railway
  requireSsl: false

# Redis
redis:
  enabled: false
  host: redis.private-production.examplepod.com
  port: 6379

maxRequestSize: 524288

sessionLogs:
  consoleEnabled: false
