name: hololine_server
description: Starting point for a Serverpod server.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  #resend: ^1.0.0
  serverpod: 2.9.1
  serverpod_auth_server: ^2.9.1
  #http: ^1.1.0
  mailer: ^6.0.1

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  serverpod_test: 2.9.1
  mockito: ^5.6.1
  test: ^1.25.6
  build_runner: ^2.10.4

